services:
  hawser:
    container_name: hawser
    image: ghcr.io/finsys/hawser:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - stacks:/data/stacks
    ports:
      - 2376:2376
volumes:
  stacks:
